In [5]:
import pandas as pd
reviews = pd.read_csv("winemag-data-130k-v2.csv")
reviews.head()

   Unnamed: 0   country  ...         variety               winery
0           0     Italy  ...     White Blend              Nicosia
1           1  Portugal  ...  Portuguese Red  Quinta dos Avidagos
2           2        US  ...      Pinot Gris            Rainstorm
3           3        US  ...        Riesling           St. Julian
4           4        US  ...      Pinot Noir         Sweet Cheeks

[5 rows x 14 columns]

Select the `description` column from reviews and assign the result to the variable `desc`.

In [6]:
desc = reviews['description']
desc

0         Aromas include tropical fruit, broom, brimston...
1         This is ripe and fruity, a wine that is smooth...
2         Tart and snappy, the flavors of lime flesh and...
3         Pineapple rind, lemon pith and orange blossom ...
4         Much like the regular bottling from 2012, this...
                                ...
129966    Notes of honeysuckle and cantaloupe sweeten th...
129967    Citation is given as much as a decade of bottl...
129968    Well-drained gravel soil gives this wine its c...
129969    A dry style of Pinot Gris, this is crisp with ...
129970    Big, rich and off-dry, this is powered by inte...
Name: description, Length: 129971, dtype: object

Select the records with index labels `1`, `2`, `3`, `5`, and `8`, assigning the result to the variable `sample_reviews`.

In [7]:
n = [1, 2, 3, 5, 8]
sample_reviews = reviews.iloc[n]
sample_reviews

   Unnamed: 0   country  ...             variety               winery
1           1  Portugal  ...      Portuguese Red  Quinta dos Avidagos
2           2        US  ...          Pinot Gris            Rainstorm
3           3        US  ...            Riesling           St. Julian
5           5     Spain  ...  Tempranillo-Merlot               Tandem
8           8   Germany  ...      Gewürztraminer          Heinz Eifel

[5 rows x 14 columns]

Create a variable `df` containing the `country`, `province`, `region_1`, and `region_2` columns of the records with the index labels `0`, `1`, `10`, and `100`.

In [8]:
columns_selected = ['country', 'province', 'region_1', 'region_2']
n_rows = [0,1,10,100]
df = reviews[columns_selected].iloc[n_rows]
df

      country           province      region_1      region_2
0       Italy  Sicily & Sardinia          Etna           NaN
1    Portugal              Douro           NaN           NaN
10         US         California   Napa Valley          Napa
100        US           New York  Finger Lakes  Finger Lakes

Create a variable `df` containing the `country` and `variety` columns of the first 100 records. 

Hint: you may use `loc` or `iloc`. When working on the answer this question and the several of the ones that follow, keep the following "gotcha" described in the tutorial:

> `iloc` uses the Python stdlib indexing scheme, where the first element of the range is included and the last one excluded. 
`loc`, meanwhile, indexes inclusively. 

> This is particularly confusing when the DataFrame index is a simple numerical list, e.g. `0,...,1000`. In this case `df.iloc[0:1000]` will return 1000 entries, while `df.loc[0:1000]` return 1001 of them! To get 1000 elements using `loc`, you will need to go one lower and ask for `df.iloc[0:999]`.

In [9]:
columns_selected = ['country','variety']
df_2 = reviews[columns_selected].iloc[0:100]
df_2

     country                   variety
0      Italy               White Blend
1   Portugal            Portuguese Red
2         US                Pinot Gris
3         US                  Riesling
4         US                Pinot Noir
..       ...                       ...
95    France                     Gamay
96    France                     Gamay
97        US                  Riesling
98     Italy                Sangiovese
99        US  Bordeaux-style Red Blend

[100 rows x 2 columns]

Create a DataFrame `top_oceania_wines` containing all reviews with at least 95 points (out of 100) for wines from Australia or New Zealand.

In [10]:
top_oceania_wines = reviews[(reviews.country.isin(['Australia', 'New Zealand']))& (reviews.points >= 95)]
top_oceania_wines

        Unnamed: 0  ...                       winery
345            345  ...  Chambers Rosewood Vineyards
346            346  ...  Chambers Rosewood Vineyards
348            348  ...  Chambers Rosewood Vineyards
349            349  ...                     Torbreck
356            356  ...                  Jasper Hill
360            360  ...                     Torbreck
365            365  ...                    Wakefield
14354        14354  ...                      Kaesler
16538        16538  ...                      Lambert
28573        28573  ...              Clarendon Hills
34502        34502  ...                     Standish
34506        34506  ...                     Standish
38988        38988  ...                     Penfolds
39059        39059  ...                    Wakefield
39961        39961  ...                     Penfolds
39962        39962  ...                     Penfolds
45809        45809  ...              Clarendon Hills
56953        56953  ...                     Penfolds
56956        56956  ...                     Standish
56957        56957  ...                 Thorn Clarke
56959        56959  ...                     Henschke
59977        59977  ...                 Hickinbotham
59984        59984  ...                    Heartland
67096        67096  ...            R.L. Buller & Son
67101        67101  ...  Chambers Rosewood Vineyards
76392        76392  ...                  Jasper Hill
77028        77028  ...                     Penfolds
77036        77036  ...                     Penfolds
77037        77037  ...                     Torbreck
77042        77042  ...             John Duval Wines
77044        77044  ...                   Kilikanoon
77046        77046  ...                     Torbreck
83357        83357  ...                     Penfolds
84815        84815  ...                     Torbreck
84816        84816  ...                     Nashwauk
87128        87128  ...                 Kay Brothers
87137        87137  ...                    Moss Wood
87143        87143  ...                    Wakefield
91851        91851  ...                 Trinity Hill
98386        98386  ...                   D'Arenberg
99318        99318  ...                     Henschke
99330        99330  ...                     Penfolds
99340        99340  ...                     Torbreck
109427      109427  ...  Chambers Rosewood Vineyards
109434      109434  ...                   D'Arenberg
122421      122421  ...                     Glaetzer
122430      122430  ...                     Glaetzer
122507      122507  ...             Squawking Magpie
122939      122939  ...                     Torbreck

[49 rows x 14 columns]

In [11]:
# Determine median value
median_points = reviews.points.median()
median_points

88.0

In [12]:
# Determine unique country list
countries = reviews.country.unique()
countries

array(['Italy', 'Portugal', 'US', 'Spain', 'France', 'Germany',
       'Argentina', 'Chile', 'Australia', 'Austria', 'South Africa',
       'New Zealand', 'Israel', 'Hungary', 'Greece', 'Romania', 'Mexico',
       'Canada', nan, 'Turkey', 'Czech Republic', 'Slovenia',
       'Luxembourg', 'Croatia', 'Georgia', 'Uruguay', 'England',
       'Lebanon', 'Serbia', 'Brazil', 'Moldova', 'Morocco', 'Peru',
       'India', 'Bulgaria', 'Cyprus', 'Armenia', 'Switzerland',
       'Bosnia and Herzegovina', 'Ukraine', 'Slovakia', 'Macedonia',
       'China', 'Egypt'], dtype=object)

Create a Series `reviews_per_country` mapping countries to the count of reviews of wines from that country.

In [13]:
reviews_per_country = reviews.country.value_counts()
reviews_per_country

US                        54504
France                    22093
Italy                     19540
Spain                      6645
Portugal                   5691
Chile                      4472
Argentina                  3800
Austria                    3345
Australia                  2329
Germany                    2165
New Zealand                1419
South Africa               1401
Israel                      505
Greece                      466
Canada                      257
Hungary                     146
Bulgaria                    141
Romania                     120
Uruguay                     109
Turkey                       90
Slovenia                     87
Georgia                      86
England                      74
Croatia                      73
Mexico                       70
Moldova                      59
Brazil                       52
Lebanon                      35
Morocco                      28
Peru                         16
Ukraine                      14
Czech Republic               12
Macedonia                    12
Serbia                       12
Cyprus                       11
India                         9
Switzerland                   7
Luxembourg                    6
Bosnia and Herzegovina        2
Armenia                       2
Egypt                         1
Slovakia                      1
China                         1
Name: country, dtype: int64

Create variable `centered_price` containing a version of the `price` column with the mean price subtracted.

In [14]:
centered_price = reviews.price - reviews.price.mean()
centered_price

0               NaN
1        -20.363389
2        -21.363389
3        -22.363389
4         29.636611
            ...
129966    -7.363389
129967    39.636611
129968    -5.363389
129969    -3.363389
129970   -14.363389
Name: price, Length: 129971, dtype: float64

Create a variable bargain_wine with the title of the wine with the highest points-to-price ratio in the dataset.

In [15]:
i = (reviews.points / reviews.price).idxmax()
bargain_wine = reviews.loc[i, 'title']
bargain_wine

'Bandit NV Merlot (California)'

In [16]:
i

64590

In [17]:
tropical_total = reviews.description.map(lambda desc: "tropical" in desc).sum()
tropical_total

3607

In [18]:
fruity_total = reviews.description.map(lambda desc: "fruity" in desc).sum()
descriptor_counts = pd.Series([tropical_total, fruity_total], index=['tropical', 'fruity'])
descriptor_counts

tropical    3607
fruity      9090
dtype: int64

In [0]:
def ratings(row):
    if row.country == 'Canada':
        return 3
    elif row.points >= 95:
        return 3
    elif row.points >= 85:
        return 2
    else:
        return 1
    
star_ratings = reviews.apply(ratings, axis='columns')

In [20]:
star_ratings

0         2
1         2
2         2
3         2
4         2
         ..
129966    2
129967    2
129968    2
129969    2
129970    2
Length: 129971, dtype: int64

Create a `Series` whose index is the `taster_twitter_handle` category from the dataset, and whose values count how many reviews each person wrote.

In [21]:
reviews_written = reviews.groupby('taster_twitter_handle').size()
reviews_written

taster_twitter_handle
@AnneInVino          3685
@JoeCz               5147
@bkfiona               27
@gordone_cellars     4177
@kerinokeefe        10776
@laurbuzz            1835
@mattkettmann        6332
@paulgwine           9532
@suskostrzewa        1085
@vboone              9537
@vossroger          25514
@wawinereport        4966
@wineschach         15134
@winewchristina         6
@worldwineguys       1005
dtype: int64

Create a `Series` whose index is wine prices and whose values is the maximum number of points a wine costing that much was given in a review. Sort the values by price, ascending (so that `4.0` dollars is at the top and `3300.0` dollars is at the bottom)

In [22]:
best_rating_per_price = reviews.groupby('price')['points'].max().sort_index()
best_rating_per_price

price
4.0       86
5.0       87
6.0       88
7.0       91
8.0       91
          ..
1900.0    98
2000.0    97
2013.0    91
2500.0    96
3300.0    88
Name: points, Length: 390, dtype: int64

Create a `DataFrame` whose index is the `variety` category from the dataset and whose values are the `min` and `max` values thereof.

In [23]:
price_extremes = reviews.groupby(['variety']).price.agg([min, max])
price_extremes

              min    max
variety
Abouriou     15.0   75.0
Agiorgitiko  10.0   66.0
Aglianico     6.0  180.0
Aidani       27.0   27.0
Airen         8.0   10.0
...           ...    ...
Zinfandel     5.0  100.0
Zlahtina     13.0   16.0
Zweigelt      9.0   70.0
Çalkarası    19.0   19.0
Žilavka      15.0   15.0

[707 rows x 2 columns]

Create a variable `sorted_varieties` containing a copy of the dataframe from the previous question where varieties are sorted in descending order based on minimum price, then on maximum price (to break ties).

In [24]:
# sort the min and max price
sorted_varieties = price_extremes.sort_values(by=['min', 'max'], ascending=False)
sorted_varieties

                                  min    max
variety
Ramisco                         495.0  495.0
Terrantez                       236.0  236.0
Francisa                        160.0  160.0
Rosenmuskateller                150.0  150.0
Tinta Negra Mole                112.0  112.0
...                               ...    ...
Roscetto                          NaN    NaN
Sauvignon Blanc-Sauvignon Gris    NaN    NaN
Tempranillo-Malbec                NaN    NaN
Vital                             NaN    NaN
Zelen                             NaN    NaN

[707 rows x 2 columns]

Create a `Series` whose index is reviewers and whose values is the average review score given out by that reviewer. Hint: you will need the `taster_name` and `points` columns.

In [25]:
reviewer_mean_ratings = reviews.groupby('taster_name')['points'].mean()
reviewer_mean_ratings

taster_name
Alexander Peartree    85.855422
Anna Lee C. Iijima    88.415629
Anne Krebiehl MW      90.562551
Carrie Dykes          86.395683
Christina Pickard     87.833333
Fiona Adams           86.888889
Jeff Jenssen          88.319756
Jim Gordon            88.626287
Joe Czerwinski        88.536235
Kerin O’Keefe         88.867947
Lauren Buzzeo         87.739510
Matt Kettmann         90.008686
Michael Schachner     86.907493
Mike DeSimone         89.101167
Paul Gregutt          89.082564
Roger Voss            88.708003
Sean P. Sullivan      88.755739
Susan Kostrzewa       86.609217
Virginie Boone        89.213379
Name: points, dtype: float64

In [26]:
reviewer_mean_ratings.describe()

count    19.000000
mean     88.233026
std       1.243610
min      85.855422
25%      87.323501
50%      88.536235
75%      88.975256
max      90.562551
Name: points, dtype: float64

Create a `Series` whose index is a `MultiIndex`of `{country, variety}` pairs. For example, a pinot noir produced in the US should map to `{"US", "Pinot Noir"}`. Sort the values in the `Series` in descending order based on wine count.

In [27]:
# since it need 'country' and 'variety', therefore groupby both
country_variety_counts = reviews.groupby(['country', 'variety']).size()
country_variety_counts

country    variety
Argentina  Barbera                         1
           Bonarda                       105
           Bordeaux-style Red Blend       89
           Bordeaux-style White Blend      1
           Cabernet Blend                  8
                                        ...
Uruguay    Tannat-Cabernet Franc           2
           Tannat-Merlot                   6
           Tannat-Syrah                    1
           Tempranillo-Tannat              1
           White Blend                     1
Length: 1612, dtype: int64

In [28]:
country_variety_counts.sort_values(ascending=False)

country    variety
US         Pinot Noir                  9885
           Cabernet Sauvignon          7315
           Chardonnay                  6801
France     Bordeaux-style Red Blend    4725
Italy      Red Blend                   3624
                                       ...
Uruguay    Tempranillo-Tannat             1
Italy      Pignolo                        1
           Muscat                         1
           Moscato di Noto                1
Argentina  Barbera                        1
Length: 1612, dtype: int64

Check how many missing value data in price column.

In [29]:
n_missing_prices = reviews.price.isnull().sum()
n_missing_prices

8996

Create a Series counting the number of times each value occurs in the `region_1` field. This field is often missing data, so replace missing values with `Unknown`. Sort in descending order.

In [38]:
produced_at = reviews.region_1.fillna('Unknown').value_counts().sort_values(ascending=False)
produced_at

Unknown                                 21247
Napa Valley                              4480
Columbia Valley (WA)                     4124
Russian River Valley                     3091
California                               2629
                                        ...
Coteaux du Lyonnais                         1
Geelong                                     1
Offida Rosso                                1
Corton Perrières                            1
Vin de Pays des Coteaux de Bessilles        1
Name: region_1, Length: 1230, dtype: int64

In [39]:
reviews

        Unnamed: 0  ...                                    winery
0                0  ...                                   Nicosia
1                1  ...                       Quinta dos Avidagos
2                2  ...                                 Rainstorm
3                3  ...                                St. Julian
4                4  ...                              Sweet Cheeks
...            ...  ...                                       ...
129966      129966  ...  Dr. H. Thanisch (Erben Müller-Burggraef)
129967      129967  ...                                  Citation
129968      129968  ...                           Domaine Gresser
129969      129969  ...                      Domaine Marcel Deiss
129970      129970  ...                          Domaine Schoffit

[129971 rows x 14 columns]

In [40]:
reviews.rename_axis("wines", axis='rows').rename_axis("fields", axis='columns')

fields  Unnamed: 0  ...                                    winery
wines               ...
0                0  ...                                   Nicosia
1                1  ...                       Quinta dos Avidagos
2                2  ...                                 Rainstorm
3                3  ...                                St. Julian
4                4  ...                              Sweet Cheeks
...            ...  ...                                       ...
129966      129966  ...  Dr. H. Thanisch (Erben Müller-Burggraef)
129967      129967  ...                                  Citation
129968      129968  ...                           Domaine Gresser
129969      129969  ...                      Domaine Marcel Deiss
129970      129970  ...                          Domaine Schoffit

[129971 rows x 14 columns]

Create a copy of `reviews` with these columns renamed to `region` and `locale`, respectively.

In [41]:
renamed = reviews.rename(columns={'region_1': 'region', 'region_2':'locale'})
renamed

        Unnamed: 0  ...                                    winery
0                0  ...                                   Nicosia
1                1  ...                       Quinta dos Avidagos
2                2  ...                                 Rainstorm
3                3  ...                                St. Julian
4                4  ...                              Sweet Cheeks
...            ...  ...                                       ...
129966      129966  ...  Dr. H. Thanisch (Erben Müller-Burggraef)
129967      129967  ...                                  Citation
129968      129968  ...                           Domaine Gresser
129969      129969  ...                      Domaine Marcel Deiss
129970      129970  ...                          Domaine Schoffit

[129971 rows x 14 columns]

Set the index name in the dataset to `wines`

In [44]:
reindexed = reviews.rename_axis('wines', axis='rows')
reindexed

        Unnamed: 0  ...                                    winery
wines               ...
0                0  ...                                   Nicosia
1                1  ...                       Quinta dos Avidagos
2                2  ...                                 Rainstorm
3                3  ...                                St. Julian
4                4  ...                              Sweet Cheeks
...            ...  ...                                       ...
129966      129966  ...  Dr. H. Thanisch (Erben Müller-Burggraef)
129967      129967  ...                                  Citation
129968      129968  ...                           Domaine Gresser
129969      129969  ...                      Domaine Marcel Deiss
129970      129970  ...                          Domaine Schoffit

[129971 rows x 14 columns]