# **Tutorial**

In this practice work, we will try using following methods to handling the missing values.

1.   Drop columns with missing values
2.   Imputation

In [0]:
import pandas as pd
from sklearn.model_selection import train_test_split

# Read the data
X_full = pd.read_csv('train.csv', index_col='Id')
X_test_full = pd.read_csv('test.csv', index_col='Id')

In [3]:
X_full

      MSSubClass MSZoning  LotFrontage  ...  SaleType SaleCondition SalePrice
Id                                      ...
1             60       RL         65.0  ...        WD        Normal    208500
2             20       RL         80.0  ...        WD        Normal    181500
3             60       RL         68.0  ...        WD        Normal    223500
4             70       RL         60.0  ...        WD       Abnorml    140000
5             60       RL         84.0  ...        WD        Normal    250000
...          ...      ...          ...  ...       ...           ...       ...
1456          60       RL         62.0  ...        WD        Normal    175000
1457          20       RL         85.0  ...        WD        Normal    210000
1458          70       RL         66.0  ...        WD        Normal    266500
1459          20       RL         68.0  ...        WD        Normal    142125
1460          20       RL         75.0  ...        WD        Normal    147500

[1460 rows x 80 columns]

Below part is perform checking rows (axis=0) for any NaN on "SalePrice" column, then drop the row. y is the copy of "SalePrice" column. Lastly, drop the "SalePrice" column in X_full.

In [4]:
# Remove rows with missing target, separate target from predictors
X_full.dropna(axis=0, subset=['SalePrice'], inplace=True)
y = X_full.SalePrice
X_full.drop(['SalePrice'], axis=1, inplace=True)

X_full

      MSSubClass MSZoning  LotFrontage  ...  YrSold SaleType SaleCondition
Id                                      ...
1             60       RL         65.0  ...    2008       WD        Normal
2             20       RL         80.0  ...    2007       WD        Normal
3             60       RL         68.0  ...    2008       WD        Normal
4             70       RL         60.0  ...    2006       WD       Abnorml
5             60       RL         84.0  ...    2008       WD        Normal
...          ...      ...          ...  ...     ...      ...           ...
1456          60       RL         62.0  ...    2007       WD        Normal
1457          20       RL         85.0  ...    2010       WD        Normal
1458          70       RL         66.0  ...    2010       WD        Normal
1459          20       RL         68.0  ...    2010       WD        Normal
1460          20       RL         75.0  ...    2008       WD        Normal

[1460 rows x 79 columns]

In [5]:
y

Id
1       208500
2       181500
3       223500
4       140000
5       250000
         ...
1456    175000
1457    210000
1458    266500
1459    142125
1460    147500
Name: SalePrice, Length: 1460, dtype: int64

In [0]:
# To keep things simple, we'll use only numerical predictors
X = X_full.select_dtypes(exclude=['object'])
X_test = X_test_full.select_dtypes(exclude=['object'])

In [7]:
X

      MSSubClass  LotFrontage  LotArea  ...  MiscVal  MoSold  YrSold
Id                                      ...
1             60         65.0     8450  ...        0       2    2008
2             20         80.0     9600  ...        0       5    2007
3             60         68.0    11250  ...        0       9    2008
4             70         60.0     9550  ...        0       2    2006
5             60         84.0    14260  ...        0      12    2008
...          ...          ...      ...  ...      ...     ...     ...
1456          60         62.0     7917  ...        0       8    2007
1457          20         85.0    13175  ...        0       2    2010
1458          70         66.0     9042  ...     2500       5    2010
1459          20         68.0     9717  ...        0       4    2010
1460          20         75.0     9937  ...        0       6    2008

[1460 rows x 36 columns]

In [0]:
# Break off validation set from training data
X_train, X_valid, y_train, y_valid = train_test_split(X, y, train_size=0.8, test_size=0.2,
                                                      random_state=0)

In [9]:
X_train.head()

     MSSubClass  LotFrontage  LotArea  ...  MiscVal  MoSold  YrSold
Id                                     ...
619          20         90.0    11694  ...        0       7    2007
871          20         60.0     6600  ...        0       8    2009
93           30         80.0    13360  ...        0       8    2009
818          20          NaN    13265  ...        0       7    2008
303          20        118.0    13704  ...        0       1    2006

[5 rows x 36 columns]

In [10]:
# Shape of training data (num_rows, num_columns)
print(X_train.shape)

# Number of missing values in each column of training data
missing_val_count_by_column = (X_train.isnull().sum())
print(missing_val_count_by_column[missing_val_count_by_column > 0])

(1168, 36)
LotFrontage    212
MasVnrArea       6
GarageYrBlt     58
dtype: int64

In [11]:
missing_val_count_by_column

MSSubClass         0
LotFrontage      212
LotArea            0
OverallQual        0
OverallCond        0
YearBuilt          0
YearRemodAdd       0
MasVnrArea         6
BsmtFinSF1         0
BsmtFinSF2         0
BsmtUnfSF          0
TotalBsmtSF        0
1stFlrSF           0
2ndFlrSF           0
LowQualFinSF       0
GrLivArea          0
BsmtFullBath       0
BsmtHalfBath       0
FullBath           0
HalfBath           0
BedroomAbvGr       0
KitchenAbvGr       0
TotRmsAbvGrd       0
Fireplaces         0
GarageYrBlt       58
GarageCars         0
GarageArea         0
WoodDeckSF         0
OpenPorchSF        0
EnclosedPorch      0
3SsnPorch          0
ScreenPorch        0
PoolArea           0
MiscVal            0
MoSold             0
YrSold             0
dtype: int64

In [13]:
# check total rows in the training data
num_rows = X_train.shape[0]
num_rows

1168

In [14]:
num_cols_with_missing = len(missing_val_count_by_column[missing_val_count_by_column > 0])
tot_missing = sum(missing_val_count_by_column[missing_val_count_by_column > 0])
print(num_cols_with_missing)
print(tot_missing)

3
276

In [0]:
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_absolute_error

# Function for comparing different approaches
def score_dataset(X_train, X_valid, y_train, y_valid):
    model = RandomForestRegressor(n_estimators=100, random_state=0)
    model.fit(X_train, y_train)
    preds = model.predict(X_valid)
    return mean_absolute_error(y_valid, preds)

In [17]:
# To check the column name which has missing value
column_missing_name = [col for col in X_train.columns if X_train[col].isnull().any()]
column_missing_name

['LotFrontage', 'MasVnrArea', 'GarageYrBlt']

# **Drop columns with missing values**

In [18]:
reduced_X_train = X_train.drop(column_missing_name,axis=1)
reduced_X_valid = X_valid.drop(column_missing_name,axis=1)

# check the data after drop columns with missing value
reduced_X_train

      MSSubClass  LotArea  OverallQual  ...  MiscVal  MoSold  YrSold
Id                                      ...
619           20    11694            9  ...        0       7    2007
871           20     6600            5  ...        0       8    2009
93            30    13360            5  ...        0       8    2009
818           20    13265            8  ...        0       7    2008
303           20    13704            7  ...        0       1    2006
...          ...      ...          ...  ...      ...     ...     ...
764           60     9430            8  ...        0       7    2009
836           20     9600            4  ...        0       2    2010
1217          90     8930            6  ...        0       4    2010
560          120     3196            7  ...        0      10    2006
685           60    16770            7  ...        0       6    2010

[1168 rows x 33 columns]

In [19]:
print("MAE (Drop columns with missing values):")
print(score_dataset(reduced_X_train, reduced_X_valid, y_train, y_valid))

MAE (Drop columns with missing values):
17837.82570776256

# **Imputation**

Based on documentation from [sklearn](https://scikit-learn.org/stable/modules/generated/sklearn.impute.SimpleImputer.html). Imputation transformer for completing missing values. It has few imputation strategy.

The imputation strategy.

* If “**mean**”, then replace missing values using the mean along each column. Can only be used with numeric data.

* If “**median**”, then replace missing values using the median along each column. Can only be used with numeric data.

* If “**most_frequent**”, then replace missing using the most frequent value along each column. Can be used with strings or numeric data.

* If “**constant**”, then replace missing values with fill_value. Can be used with strings or numeric data.

In [0]:
from sklearn.impute import SimpleImputer

my_imputer = SimpleImputer()
imputed_X_train = pd.DataFrame(my_imputer.fit_transform(X_train))
imputed_X_valid = pd.DataFrame(my_imputer.transform(X_valid))

In [24]:
imputed_X_train

         0           1        2    3    4   ...     31   32   33    34      35
0      20.0   90.000000  11694.0  9.0  5.0  ...  260.0  0.0  0.0   7.0  2007.0
1      20.0   60.000000   6600.0  5.0  5.0  ...    0.0  0.0  0.0   8.0  2009.0
2      30.0   80.000000  13360.0  5.0  7.0  ...    0.0  0.0  0.0   8.0  2009.0
3      20.0   69.614017  13265.0  8.0  5.0  ...    0.0  0.0  0.0   7.0  2008.0
4      20.0  118.000000  13704.0  7.0  5.0  ...    0.0  0.0  0.0   1.0  2006.0
...     ...         ...      ...  ...  ...  ...    ...  ...  ...   ...     ...
1163   60.0   82.000000   9430.0  8.0  5.0  ...  180.0  0.0  0.0   7.0  2009.0
1164   20.0   60.000000   9600.0  4.0  7.0  ...    0.0  0.0  0.0   2.0  2010.0
1165   90.0   68.000000   8930.0  6.0  5.0  ...    0.0  0.0  0.0   4.0  2010.0
1166  120.0   69.614017   3196.0  7.0  5.0  ...    0.0  0.0  0.0  10.0  2006.0
1167   60.0   58.000000  16770.0  7.0  5.0  ...    0.0  0.0  0.0   6.0  2010.0

[1168 rows x 36 columns]

In [0]:
# after imputation, the column names were removed, therefore need to assign the column name
imputed_X_train.columns = X_train.columns
imputed_X_valid.columns = X_valid.columns

In [26]:
imputed_X_train

      MSSubClass  LotFrontage  LotArea  ...  MiscVal  MoSold  YrSold
0           20.0    90.000000  11694.0  ...      0.0     7.0  2007.0
1           20.0    60.000000   6600.0  ...      0.0     8.0  2009.0
2           30.0    80.000000  13360.0  ...      0.0     8.0  2009.0
3           20.0    69.614017  13265.0  ...      0.0     7.0  2008.0
4           20.0   118.000000  13704.0  ...      0.0     1.0  2006.0
...          ...          ...      ...  ...      ...     ...     ...
1163        60.0    82.000000   9430.0  ...      0.0     7.0  2009.0
1164        20.0    60.000000   9600.0  ...      0.0     2.0  2010.0
1165        90.0    68.000000   8930.0  ...      0.0     4.0  2010.0
1166       120.0    69.614017   3196.0  ...      0.0    10.0  2006.0
1167        60.0    58.000000  16770.0  ...      0.0     6.0  2010.0

[1168 rows x 36 columns]

In [27]:
print("MAE (Imputation):")
print(score_dataset(imputed_X_train, imputed_X_valid, y_train, y_valid))

MAE (Imputation):
18062.894611872147

Surprisingly, the method of dropping column is perform slightly better than imputation method. This may because of:

1.  There is noise in the dataset
2.  The data is not suitable to using imputation since not every missing data is consider approach to mean value.

In [0]:
final_imputer = SimpleImputer(strategy='median')
# Preprocessed training and validation features
final_X_train = pd.DataFrame(final_imputer.fit_transform(X_train))
final_X_valid = pd.DataFrame(final_imputer.transform(X_valid))

In [29]:
type(final_X_train)

pandas.core.frame.DataFrame

In [0]:
final_X_train.columns = X_train.columns
final_X_valid.columns = X_valid.columns

In [32]:
model = RandomForestRegressor(n_estimators=100, criterion='mse', random_state=0)
model.fit(final_X_train, y_train)

pred_valid = model.predict(final_X_valid)
print("MAE: ")
print(mean_absolute_error(y_valid, pred_valid))

MAE:
17791.59899543379